### ISSUE TITLE
Visual Theme System: Public Files

### ISSUE THREAD

**Issue by tapanbavaliya** [Improwised/BookStack#9]
### Describe the feature you'd like

`https://github.com/BookStackApp/BookStack/issues/3904`

### Describe the benefits this would bring to existing BookStack users

-

### Can the goal of this request already be achieved via other means?

-

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

### How long have you been using BookStack?

Not using yet, just scoping

### Additional context

-

**Comment by brij-mandaliya** [comment]
Implementation  Time : 8 Hours
Exploration Time : 4 Hours

**Comment by brij-mandaliya** [comment]
Implementation Start

**Comment by brij-mandaliya** [comment]
Discussion on weekly (7-10-2024)

- right now file is store with filename only, the issue might be arise that two different person can upload file with same name then latest file will be override to previous file
    - solution : store file name with some random string or any hash value
    
-  Exploration:
   - till now we dont store custom file into database, if we move from local storage to any cloud storage then we have database store then it very convenient  to manage custom files

**Comment by brij-mandaliya** [comment]
Discussion on (9-10-24)

- discuss about why database is need
- we create a migration for move from local storage to s3 and vice-versa
- now onwards no need for database firstly try to apply custom added css file into project.
- apply as other css do not affect rather than only in file css is update

**Comment by brij-mandaliya** [comment]
we need to discuss about the issue in more depth
